#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_THEME=Arc-Dark-solid

cd ~ || exit
sxhkd &
dunst &
picom &
polybar &
light-locker &
feh --no-fehbg --bg-fill /etc/xdg/background.png &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#5294E2"
bspc config normal_border_color "#4b5162"
bspc config ignore_ewmh_focus true
bspc config automatic_scheme longest_side
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a Screenkey manage=off
bspc rule -a xfce4-panel manage=off
bspc rule -a discord desktop='^9'
bspc rule -a Steam desktop='^10' state=floating
bspc rule -a Zenity desktop='^10' state=floating
bspc rule -a Gimp desktop='^10' state=floating follow=on
bspc rule -a Nm-connection-editor state=floating
bspc rule -a firefox:Toolkit sticky=on state=floating layer=above rectangle=320x180+1584+884
