[colors.primary]
background = "#2F343F"
foreground = "#A7ADBA"

[cursor]
style = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10

[font.normal]
family = "RobotoMono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Shift|Control"

[scrolling]
history = 10000

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 125
lines = 37

[window.padding]
x = 5
y = 5
